
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLASS DEF NUMBER RETURN VARIABLEprogram : statementsstatements : statements statement\n                  | statement statement : assignment\n                  | operation\n                  | function\n                  | runfunction\n                  | class\n    assignment : VARIABLE \'.\' VARIABLE \'=\' VARIABLE\n                  | VARIABLE \'=\' VARIABLE \'(\' string \',\' numbers \')\'\n    string : "\'" VARIABLE "\'" numbers : numbers \',\' NUMBER\n               | NUMBER\n    operation : VARIABLE \'.\' VARIABLE \'=\' VARIABLE \'.\' VARIABLE \'+\' VARIABLEfunction : DEF VARIABLE \'(\' variables \')\' \'{\' statements RETURN VARIABLE \'}\'\n                 | DEF VARIABLE \'(\' variables \')\' \'{\' statements \'}\'\n    variables : variables \',\' VARIABLE\n                 | VARIABLE\n    runfunction : VARIABLE \'(\' variables \')\'\n                    | VARIABLE \'.\' VARIABLE \'(\' numbers \')\'\n                    | VARIABLE \'.\' VARIABLE \'(\' \')\'\n    class : CLASS VARIABLE \'{\' functions \'}\' functions : functions function\n                 | function\n    '
    
_lr_action_items = {'VARIABLE':([0,2,3,4,5,6,7,8,10,11,12,13,14,15,22,24,27,28,32,34,37,40,42,43,47,52,53,54,55,56,57,59,],[9,9,-3,-4,-5,-6,-7,-8,16,17,-2,18,19,20,20,32,-19,38,-9,-21,46,-22,48,-20,9,9,57,-10,58,-16,-14,-15,]),'DEF':([0,2,3,4,5,6,7,8,12,23,27,30,31,32,34,40,41,43,47,52,54,56,57,59,],[10,10,-3,-4,-5,-6,-7,-8,-2,10,-19,10,-24,-9,-21,-22,-23,-20,10,10,-10,-16,-14,-15,]),'CLASS':([0,2,3,4,5,6,7,8,12,27,32,34,40,43,47,52,54,56,57,59,],[11,11,-3,-4,-5,-6,-7,-8,-2,-19,-9,-21,-22,-20,11,11,-10,-16,-14,-15,]),'$end':([1,2,3,4,5,6,7,8,12,27,32,34,40,43,54,56,57,59,],[0,-1,-3,-4,-5,-6,-7,-8,-2,-19,-9,-21,-22,-20,-10,-16,-14,-15,]),'RETURN':([3,4,5,6,7,8,12,27,32,34,40,43,52,54,56,57,59,],[-3,-4,-5,-6,-7,-8,-2,-19,-9,-21,-22,-20,55,-10,-16,-14,-15,]),'}':([3,4,5,6,7,8,12,27,30,31,32,34,40,41,43,52,54,56,57,58,59,],[-3,-4,-5,-6,-7,-8,-2,-19,40,-24,-9,-21,-22,-23,-20,56,-10,-16,-14,59,-15,]),'.':([9,32,],[13,42,]),'=':([9,18,],[14,24,]),'(':([9,16,18,19,],[15,22,25,26,]),'{':([17,39,],[23,47,]),')':([20,21,25,29,33,35,38,49,50,],[-18,27,34,39,43,-13,-17,-12,54,]),',':([20,21,29,33,35,36,38,49,50,51,],[-18,28,28,44,-13,45,-17,-12,44,-11,]),'NUMBER':([25,44,45,],[35,49,35,]),"'":([26,46,],[37,51,]),'+':([48,],[53,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,47,],[2,52,]),'statement':([0,2,47,52,],[3,12,3,12,]),'assignment':([0,2,47,52,],[4,4,4,4,]),'operation':([0,2,47,52,],[5,5,5,5,]),'function':([0,2,23,30,47,52,],[6,6,31,41,6,6,]),'runfunction':([0,2,47,52,],[7,7,7,7,]),'class':([0,2,47,52,],[8,8,8,8,]),'variables':([15,22,],[21,29,]),'functions':([23,],[30,]),'numbers':([25,45,],[33,50,]),'string':([26,],[36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','py_yacc.py',16),
  ('statements -> statements statement','statements',2,'p_statements','py_yacc.py',22),
  ('statements -> statement','statements',1,'p_statements','py_yacc.py',23),
  ('statement -> assignment','statement',1,'p_statement','py_yacc.py',33),
  ('statement -> operation','statement',1,'p_statement','py_yacc.py',34),
  ('statement -> function','statement',1,'p_statement','py_yacc.py',35),
  ('statement -> runfunction','statement',1,'p_statement','py_yacc.py',36),
  ('statement -> class','statement',1,'p_statement','py_yacc.py',37),
  ('assignment -> VARIABLE . VARIABLE = VARIABLE','assignment',5,'p_assignment','py_yacc.py',44),
  ('assignment -> VARIABLE = VARIABLE ( string , numbers )','assignment',8,'p_assignment','py_yacc.py',45),
  ("string -> ' VARIABLE '",'string',3,'p_string','py_yacc.py',62),
  ('numbers -> numbers , NUMBER','numbers',3,'p_numbers','py_yacc.py',68),
  ('numbers -> NUMBER','numbers',1,'p_numbers','py_yacc.py',69),
  ('operation -> VARIABLE . VARIABLE = VARIABLE . VARIABLE + VARIABLE','operation',9,'p_operation','py_yacc.py',81),
  ('function -> DEF VARIABLE ( variables ) { statements RETURN VARIABLE }','function',10,'p_function','py_yacc.py',87),
  ('function -> DEF VARIABLE ( variables ) { statements }','function',8,'p_function','py_yacc.py',88),
  ('variables -> variables , VARIABLE','variables',3,'p_variables','py_yacc.py',105),
  ('variables -> VARIABLE','variables',1,'p_variables','py_yacc.py',106),
  ('runfunction -> VARIABLE ( variables )','runfunction',4,'p_runfunction','py_yacc.py',118),
  ('runfunction -> VARIABLE . VARIABLE ( numbers )','runfunction',6,'p_runfunction','py_yacc.py',119),
  ('runfunction -> VARIABLE . VARIABLE ( )','runfunction',5,'p_runfunction','py_yacc.py',120),
  ('class -> CLASS VARIABLE { functions }','class',5,'p_class','py_yacc.py',134),
  ('functions -> functions function','functions',2,'p_functions','py_yacc.py',145),
  ('functions -> function','functions',1,'p_functions','py_yacc.py',146),
]
