
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER PRINT VARIABLEprogram : statementsstatements : statements statement\n                  | statement statement : assignment\n                  | operation\n                  | printassignment : VARIABLE '=' NUMBERoperation : VARIABLE '=' expressionexpression : expression '+' term\n                  | expression '-' term\n                  | term\n    term : term '*' factor\n            | term '/' factor\n            | factor\n    factor : VARIABLE\n              | '(' expression ')'\n              | NUMBER\n    variables : variables ',' VARIABLE\n                 | VARIABLE\n    print : PRINT '(' variables ')' "
    
_lr_action_items = {'VARIABLE':([0,2,3,4,5,6,9,10,11,12,13,14,15,16,17,20,21,22,23,25,26,27,28,29,30,31,32,],[7,7,-3,-4,-5,-6,-2,12,19,-15,-7,-8,-11,-14,12,12,12,12,12,-17,-20,33,-9,-10,-12,-13,-16,]),'PRINT':([0,2,3,4,5,6,9,12,13,14,15,16,25,26,28,29,30,31,32,],[8,8,-3,-4,-5,-6,-2,-15,-7,-8,-11,-14,-17,-20,-9,-10,-12,-13,-16,]),'$end':([1,2,3,4,5,6,9,12,13,14,15,16,25,26,28,29,30,31,32,],[0,-1,-3,-4,-5,-6,-2,-15,-7,-8,-11,-14,-17,-20,-9,-10,-12,-13,-16,]),'=':([7,],[10,]),'(':([8,10,17,20,21,22,23,],[11,17,17,17,17,17,17,]),'NUMBER':([10,17,20,21,22,23,],[13,25,25,25,25,25,]),'*':([12,13,15,16,25,28,29,30,31,32,],[-15,-17,22,-14,-17,22,22,-12,-13,-16,]),'/':([12,13,15,16,25,28,29,30,31,32,],[-15,-17,23,-14,-17,23,23,-12,-13,-16,]),'+':([12,13,14,15,16,24,25,28,29,30,31,32,],[-15,-17,20,-11,-14,20,-17,-9,-10,-12,-13,-16,]),'-':([12,13,14,15,16,24,25,28,29,30,31,32,],[-15,-17,21,-11,-14,21,-17,-9,-10,-12,-13,-16,]),')':([12,15,16,18,19,24,25,28,29,30,31,32,33,],[-15,-11,-14,26,-19,32,-17,-9,-10,-12,-13,-16,-18,]),',':([18,19,33,],[27,-19,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,9,]),'assignment':([0,2,],[4,4,]),'operation':([0,2,],[5,5,]),'print':([0,2,],[6,6,]),'expression':([10,17,],[14,24,]),'term':([10,17,20,21,],[15,15,28,29,]),'factor':([10,17,20,21,22,23,],[16,16,16,16,30,31,]),'variables':([11,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','py_yacc.py',18),
  ('statements -> statements statement','statements',2,'p_statements','py_yacc.py',25),
  ('statements -> statement','statements',1,'p_statements','py_yacc.py',26),
  ('statement -> assignment','statement',1,'p_statement','py_yacc.py',37),
  ('statement -> operation','statement',1,'p_statement','py_yacc.py',38),
  ('statement -> print','statement',1,'p_statement','py_yacc.py',39),
  ('assignment -> VARIABLE = NUMBER','assignment',3,'p_assignment','py_yacc.py',46),
  ('operation -> VARIABLE = expression','operation',3,'p_operation','py_yacc.py',55),
  ('expression -> expression + term','expression',3,'p_expression','py_yacc.py',63),
  ('expression -> expression - term','expression',3,'p_expression','py_yacc.py',64),
  ('expression -> term','expression',1,'p_expression','py_yacc.py',65),
  ('term -> term * factor','term',3,'p_term','py_yacc.py',77),
  ('term -> term / factor','term',3,'p_term','py_yacc.py',78),
  ('term -> factor','term',1,'p_term','py_yacc.py',79),
  ('factor -> VARIABLE','factor',1,'p_factor','py_yacc.py',91),
  ('factor -> ( expression )','factor',3,'p_factor','py_yacc.py',92),
  ('factor -> NUMBER','factor',1,'p_factor','py_yacc.py',93),
  ('variables -> variables , VARIABLE','variables',3,'p_variables','py_yacc.py',105),
  ('variables -> VARIABLE','variables',1,'p_variables','py_yacc.py',106),
  ('print -> PRINT ( variables )','print',4,'p_print','py_yacc.py',118),
]
